server:
  port: 9000

logging:
  level:
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: https://jjubul-auth.duckdns.org



      client:
        registration:
          kakao:
            client_id: 4669985b9b5311232c052c08ba9aa67d
            client-secret: ksxiB96VlzlFAWP0wEyg4jsXzxV7pZCs
            redirect-uri: https://jjubul-auth.duckdns.org/auth/kakao/callback
#            redirect-uri: http://localhost:9000/auth/kakao/callback
            scope: openid
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            provider: kakao

          google:
            client-id: 1097725503933-9lpcecr1lipovuhue8k7fcq8evakcksm.apps.googleusercontent.com
            client-secret: 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
            scope: openid
            provider: google
            redirect-uri: https://jjubul-auth.duckdns.org/auth/google/callback
#            redirect-uri: http://localhost:9000/auth/google/callback

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            issuer-uri: https://kauth.kakao.com
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json

  datasource:
    url: ${CORE_DB_URL}
    username: ${CORE_DB_USERNAME}
    password: ${CORE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

